# Halton采样
scipy.stats.qmc.Halton的random()方法会自动维护序列的状态，每次调用random(n)都会生成下一组不重复的点，确保不会重复使用采样点。

与Python不同的是，MATLAB中需要显式设置Skip来避免重复使用点。但在MATLAB中，不论是否进行scramble，生成的第一组点永远是0，可以使用Skip对0进行跳过。

目前无法确认scipy.stats.qmc.Halton中设置scramble=True是否会生成0。

In [7]:
import numpy as np
from scipy.stats import qmc

np.random.seed(42)

In [8]:
halton = qmc.Halton(5, scramble=True, seed=42)

In [9]:
halton.random(5)

array([[0.55130587, 0.73772158, 0.93945943, 0.4461684 , 0.58620524],
       [0.05130587, 0.40438825, 0.53945943, 0.30331126, 0.67711433],
       [0.80130587, 0.07105492, 0.73945943, 0.87473983, 0.04075069],
       [0.30130587, 0.9599438 , 0.33945943, 0.58902555, 0.9498416 ],
       [0.67630587, 0.62661047, 0.13945943, 0.16045412, 0.31347796]])

In [10]:
halton.random(5)

array([[0.17630587, 0.29327714, 0.81945943, 0.73188269, 0.49529614],
       [0.92630587, 0.84883269, 0.41945943, 0.01759698, 0.22256887],
       [0.42630587, 0.51549936, 0.61945943, 0.48698473, 0.40438705],
       [0.61380587, 0.18216603, 0.21945943, 0.34412759, 0.85893251],
       [0.11380587, 0.77475862, 0.01945943, 0.91555616, 0.13165978]])

In [11]:
halton.reset()

In [12]:
halton.random(10)

array([[0.55130587, 0.73772158, 0.93945943, 0.4461684 , 0.58620524],
       [0.05130587, 0.40438825, 0.53945943, 0.30331126, 0.67711433],
       [0.80130587, 0.07105492, 0.73945943, 0.87473983, 0.04075069],
       [0.30130587, 0.9599438 , 0.33945943, 0.58902555, 0.9498416 ],
       [0.67630587, 0.62661047, 0.13945943, 0.16045412, 0.31347796],
       [0.17630587, 0.29327714, 0.81945943, 0.73188269, 0.49529614],
       [0.92630587, 0.84883269, 0.41945943, 0.01759698, 0.22256887],
       [0.42630587, 0.51549936, 0.61945943, 0.48698473, 0.40438705],
       [0.61380587, 0.18216603, 0.21945943, 0.34412759, 0.85893251],
       [0.11380587, 0.77475862, 0.01945943, 0.91555616, 0.13165978]])