# NumPy

## 数组属性

| 属性            | 描述                                                                 |
|-----------------|----------------------------------------------------------------------|
| `ndarray.ndim`  | 数组的秩（rank），即数组的维度数量或轴的数量。                       |
| `ndarray.shape` | 数组的维度，表示数组在每个轴上的大小。对于二维数组（矩阵），表示其行数和列数。 |
| `ndarray.size`  | 数组中元素的总个数，等于 `ndarray.shape` 中各个轴上大小的乘积。      |


### *ndarray.ndim*
*ndarray.ndim* 用于获取数组的维度数量（即数组的轴数）。

In [ ]:
import numpy as np

a = np.arange(24)  
print (a.ndim)          # a 现只有一个维度       
b = a.reshape(2,4,3)    # 现在调整其大小
print (b.ndim)          # b 现在拥有三个维度

1
3


### *ndarray.shape*
*ndarray.shape* 表示数组的维度，返回一个元组，这个元组的长度就是维度的数目，即 ndim 属性(秩)。比如，一个二维数组，其维度表示"行数"和"列数"。

In [52]:
a = np.array([[1,2,3],[4,5,6]])  
print (a.shape)

(2, 3)


*ndarray.shape* 也可以用于调整数组大小。

In [53]:
a = np.array([[1,2,3],[4,5,6]]) 
a.shape =  (3,2)  
print (a)

[[1 2]
 [3 4]
 [5 6]]


NumPy 也提供了 reshape 函数来调整数组大小。

In [54]:
a = np.array([[1,2,3],[4,5,6]]) 
b = a.reshape(3,2)  
print (b)

[[1 2]
 [3 4]
 [5 6]]


## 切片和索引

### *slice()* 切片

ndarray 数组可以基于 0 - n 的下标进行索引，切片对象可以通过内置的 *slice* 函数，并设置 start, stop 及 step 参数进行，从原数组中切割出一个新数组。

In [55]:
a = np.arange(10)
s = slice(2,7,2)   # 从索引 2 开始到索引 7 停止，间隔为2
print (a[s])

[2 4 6]


以上实例中，我们首先通过 arange() 函数创建 ndarray 对象。 然后，分别设置起始，终止和步长的参数为 2，7 和 2。

我们也可以通过冒号分隔切片参数 start:stop:step 来进行切片操作：

In [56]:
a = np.arange(10)  
b = a[2:7:2]   # 从索引 2 开始到索引 7 停止，间隔为 2
print(b)

[2 4 6]


### 整数数组索引
整数数组索引是指使用一个数组来访问另一个数组的元素。这个数组中的每个元素都是目标数组中某个维度上的索引值。

以下实例获取数组中 (0,0)，(1,1) 和 (2,0) 位置处的元素。

In [57]:
x = np.array([[1,  2],  
              [3,  4],  
              [5,  6]]) 
y = x[[0, 1, 2],  
      [0, 1, 0]]  
print (y)

[1 4 5]


以下实例获取了 4X3 数组中的四个角的元素。 行索引是 [0,0] 和 [3,3]，而列索引是 [0,2] 和 [0,2]。

In [58]:
x = np.array([[  0,  1,  2],[  3,  4,  5],[  6,  7,  8],[  9,  10,  11]])  
print ('我们的数组是：' )
print (x)
print ('\n')
rows = np.array([[0,0],[3,3]]) 
cols = np.array([[0,2],[0,2]]) 
y = x[rows,cols]  
print  ('这个数组的四个角元素是：')
print (y)

我们的数组是：
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


这个数组的四个角元素是：
[[ 0  2]
 [ 9 11]]


### 布尔索引
布尔索引通过布尔运算（如：比较运算符）来获取符合指定条件的元素的数组。

In [59]:
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])  
print ('我们的数组是：')
print (x)
print ('\n')
# 现在我们会打印出大于 5 的元素  
print  ('大于 5 的元素是：')
print (x[x > 5])

我们的数组是：
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


大于 5 的元素是：
[ 6  7  8  9 10 11]


#### *np.where()* 按条件替换值
*np.where()* 是 NumPy 中的一个非常有用的函数，主要用于根据条件选择元素或者进行条件替换。它的基本用法有两种形式：

1. 基本形式：选择元素

   *np.where(condition, x, y)*  

 - condition: 布尔条件，可以是一个布尔数组或一个布尔表达式。数组中每个元素对应一个条件。
 - x: 满足条件时返回的值。
 - y: 不满足条件时返回的值。

In [60]:
arr = np.array([1, 2, 3, 4, 5])

# 如果元素大于 3，替换为 10，否则替换为 0
result = np.where(arr > 3, 10, 0)
print(result)

[ 0  0  0 10 10]


2. 索引位置形式：获取满足条件的索引

   *np.where(condition)*  

 - 这种形式返回的是满足条件的元素的索引（元组形式）。对于多维数组，它会返回每个维度的索引。

In [61]:
arr = np.array([1, 2, 3, 4, 5])

# 查找大于 3 的元素的索引位置
indices = np.where(arr > 3)
print(indices)

(array([3, 4], dtype=int64),)


3. 多维数组中的使用

   *np.where(condition)*  

 - 在多维数组中，*np.where()* 同样适用。它会分别返回每一维上满足条件的索引。

In [62]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

# 查找大于 5 的元素的索引位置
indices = np.where(arr > 5)
print(indices)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))


### 花式索引

*np.ix_* 函数就是输入两个数组，产生笛卡尔积的映射关系。

笛卡尔乘积是指在数学中，两个集合 X 和 Y 的笛卡尔积（Cartesian product），又称直积，表示为 X×Y，第一个对象是X的成员而第二个对象是 Y 的所有可能有序对的其中一个成员。

例如 *A={a,b}, B={0,1,2}*，则：

*A×B={(a, 0), (a, 1), (a, 2), (b, 0), (b, 1), (b, 2)}  
B×A={(0, a), (0, b), (1, a), (1, b), (2, a), (2, b)}*

In [63]:
x=np.arange(32).reshape((8,4))
print(x)
print(x[np.ix_([1,5,7,2],[0,3,1,2])])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


x[np.ix_([1,5,7,2],[0,3,1,2])]这句话会输出一个4*4的矩阵，其中的元素分别是：

x[1,0] x[1,3] x[1,1] x[1,2]  
x[5,0] x[5,3] x[5,1] x[5,2]  
x[7,0] x[7,3] x[7,1] x[7,2]  
x[2,0] x[2,3] x[2,1] x[2,2]  

就是说，如果 np.xi_ 中输入两个列表，则第一个列表存的是待提取元素的行标，第二个列表存的是待提取元素的列标，第一个列表中的每个元素都会遍历第二个列表中的每个值，构成新矩阵的一行元素。

## 数组操作
Numpy 中包含了一些函数用于处理数组，大概可分为以下几类：修改数组形状、翻转数组、修改数组维度、连接数组、分割数组、数组元素的添加与删除。

### [Numpy 数组操作](https://www.runoob.com/numpy/numpy-array-manipulation.html)

## 随机数和随机操作
*np.random.seed()* 当我们设置相同的seed，每次生成的随机数相同。如果不设置seed，则每次会生成不同的随机数。

In [67]:
np.random.seed(0)

### 随机数生成
*np.random.rand()* 生成一个0到1之间的**均匀分布**。  
*np.random.randn()* 返回一个符合标准**正态分布**的数组。  
*np.random.randint()* 返回一定范围的一维或者多维整数。 

In [75]:
print(np.random.rand(3, 2))
print(np.random.randn(3, 2))
print(np.random.randint(low=-5, high=5, size=10))

[[0.84114013 0.90464774]
 [0.03755938 0.50831545]
 [0.16684751 0.77905102]]
[[-0.2524676   1.03984679]
 [-0.02347953  0.08942229]
 [-0.59432737 -0.10569679]]
[-2  4  2  2  0 -4 -3 -3  3 -4]


### 随机操作
*np.random.choice* 从给定的一维数组中随机选择数生成随机数。  
*np.random.normal(loc=0.0, scale=1.0, size=None)* 生成符合指定分布的正态分布。  
*np.random.shuffle(x)* 随机打乱数组顺序。  

In [104]:
data = np.array([2,1,3,4,6])
print("选一个：", np.random.choice(data))
print("选多个：", np.random.choice(data, size=3))
print("不重复地选多个(不放回)：", np.random.choice(data, size=3, replace=False))
print("带权重地选择：", np.random.choice(data, size=10, p=[0,0,0,0.2,0.8]))

选一个： 6
选多个： [2 3 1]
不重复地选多个(不放回)： [6 1 4]
带权重地选择： [4 6 4 4 6 4 6 6 6 6]


In [112]:
data_copy = np.copy(data)
np.random.shuffle(data)
print("源数据：", data_copy)
print("shuffled:", data)

源数据： [3 6 2 1 4]
shuffled: [6 3 1 4 2]


## 副本和视图
副本 *copy()* 是一个数据的完整的拷贝，如果我们对副本进行修改，它不会影响到原始数据，物理内存不在同一位置。

视图 *view()* 是数据的一个别称或引用，通过该别称或引用亦便可访问、操作原有数据，但原有数据不会产生拷贝。如果我们对视图进行修改，它会影响到原始数据，物理内存在同一位置。

### [NumPy副本和视图](https://www.runoob.com/numpy/numpy-copies-and-views.html)